
let accessCode="";const totalRecords=document.getElementById("totalRecords"),code=document.getElementById("code"),eye=document.getElementById("eye"),accessMsg=document.getElementById("accessMsg"),unlock=document.getElementById("unlock"),area=document.getElementById("area"),q=document.getElementById("q"),go=document.getElementById("go"),results=document.getElementById("results"),list=document.getElementById("list"),status=document.getElementById("status"),lock=document.getElementById("lock");
eye.onclick=()=>{const showing=code.type==="text";code.type=showing?"password":"text";eye.textContent=showing?"◉":"◉";eye.setAttribute("aria-label",showing?"Tunjukkan password":"Sembunyikan password");eye.title=showing?"Tunjukkan password":"Sembunyikan password";};
unlock.onclick=async()=>{const entered=code.value.trim();if(!entered){accessMsg.textContent="Sila masukkan access code.";accessMsg.className="access-msg err";return}unlock.disabled=true;unlock.textContent="SEMAK…";accessMsg.textContent="Mengesahkan access code…";accessMsg.className="access-msg";try{const r=await fetch("/api/search",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"auth",code:entered})});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||"Access code tidak sah.");accessCode=entered;if(d.totalRecords)totalRecords.textContent=d.totalRecords;area.classList.remove("hidden");code.disabled=true;unlock.textContent="AKSES ✓";accessMsg.textContent="✓ Akses berjaya. Sistem carian telah dibuka.";accessMsg.className="access-msg ok";lock.classList.remove("hidden");q.focus()}catch(e){accessMsg.textContent=e.message==="Access code tidak sah."?"✕ Access code salah. Sila cuba semula.":"✕ "+e.message;accessMsg.className="access-msg err";unlock.disabled=false;unlock.textContent="AKSES"}};
code.onkeydown=e=>{if(e.key==="Enter")unlock.click()};go.onclick=search;q.onkeydown=e=>{if(e.key==="Enter")search()};
async function search(){let term=q.value.trim();if(term.length<2){results.classList.remove("hidden");status.textContent="Masukkan sekurang-kurangnya 2 aksara.";list.innerHTML="";return}go.disabled=true;status.textContent="Mencari…";results.classList.remove("hidden");list.innerHTML="";try{let r=await fetch("/api/search",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code:accessCode,q:term})}),d=await r.json();if(!r.ok)throw Error(d.error||"Carian gagal.");if(d.totalRecords)totalRecords.textContent=d.totalRecords;status.textContent=`${d.total} padanan dijumpai.`;list.innerHTML=d.results.map(x=>`<article class="result"><div class="name">${esc(x.name)}</div><div class="class">${esc(x.class)}</div><div class="idrow"><div><div class="idlabel">ID DELIMa</div><div class="id">${esc(x.id)}</div></div><button class="copy" onclick="copyId('${attr(x.id)}',this)">COPY ID</button></div></article>`).join("")||'<div class="empty">Tiada murid dijumpai. Cuba nama yang lain.</div>'}catch(e){status.textContent=e.message;list.innerHTML='<div class="empty">Carian tidak dapat diproses.</div>'}go.disabled=false}
function copyId(id,b){navigator.clipboard.writeText(id).then(()=>{let t=b.textContent;b.textContent="COPIED ✓";setTimeout(()=>b.textContent=t,1300)})}lock.onclick=()=>{accessCode="";code.value="";accessMsg.textContent="";accessMsg.className="access-msg";code.type="password";code.disabled=false;unlock.disabled=false;unlock.textContent="AKSES";area.classList.add("hidden");results.classList.add("hidden");lock.classList.add("hidden");q.value="";list.innerHTML="";eye.setAttribute("aria-label","Tunjukkan password");eye.title="Tunjukkan password";code.focus()};
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function attr(s){return String(s).replace(/\\/g,"\\\\").replace(/'/g,"\\'")}
